name: campus_digital

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^3.3.4
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_animate: ^4.5.0
  speech_to_text: ^7.0.0
  google_maps_flutter: ^2.12.3

flutter:
  uses-material-design: true