name: campus_digital_twin_ai
description: "Campus Digital Twin AI - Your smart campus companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  google_maps_flutter: ^2.18.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  speech_to_text: ^7.4.0
  google_sign_in: ^6.2.2
  share_plus: ^13.3.0
  image_picker: ^1.2.3
  gal: ^2.3.3 # for save image in gallery
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/campus/